name: Homebridge
version: 2024-12-19-beta
stage: experimental
slug: homebridge
panel_icon: mdi:hub
homeassistant_api: true
homeassistant: 2024.1.0
description: Lightweight HomeKit API implementation with plugin support
url: https://github.com/myevit/hassio-addons/tree/main/homebridge
arch:
  - armv7
  - aarch64
  - amd64
ports:
  8581/tcp: 8581
ports_description:
  8581/tcp: Homebridge UI
host_network: true
init: false
map:
  - addon_config:rw
image: myevit/hassio-homebridge-addon
ingress: true
ingress_port: 8581
