name: Homebridge
version: 2025-06-10
stage: experimental
slug: homebridge
panel_icon: mdi:hub
panel_title: Homebridge
homeassistant_api: true
homeassistant: 2024.1.0
startup: services
description: Lightweight HomeKit API implementation with plugin support
url: https://github.com/myevit/hassio-addons/tree/main/homebridge
arch:
  - armv7
  - aarch64
  - amd64
host_network: true
init: false
map:
  - addon_config:rw
image: myevit/hassio-homebridge-addon
memory: 4096
ingress: true
ingress_port: 8581
ingress_stream: true
